### ISSUE TITLE
[BUG]Example can not run in my environment

### ISSUE THREAD

**Issue by harazono** [iwasakishuto/Translation-Gummy#11]
Hi

Thanks for developing awesome tool!
I find that `gummy-translate` failed to build remote driver and failed to use `nltk`.
How can I solve it?

I'm using OS X.
```
🍵~$ gummy-translate "This is a pen."
[success] local driver can be built.
[failure] remote driver can't be built.
DRIVER_TYPE: local
DRIVER_TYPE: local
Traceback (most recent call last):
  File "/usr/local/bin/gummy-translate", line 8, in <module>
    sys.exit(translate_text())
  File "/usr/local/lib/python3.8/site-packages/gummy/cli.py", line 80, in translate_text
    japanese = model.en2ja(query=query)
  File "/usr/local/lib/python3.8/site-packages/gummy/models.py", line 27, in en2ja
    return self.translator.en2ja(query=query, driver=self.driver, barname=barname)
  File "/usr/local/lib/python3.8/site-packages/gummy/translators.py", line 89, in en2ja
    for i,q in enumerate(gen):
  File "/usr/local/lib/python3.8/site-packages/gummy/utils/generic_utils.py", line 88, in splitted_query_generator
    sent_tokenized_query = sent_tokenize(query)
  File "/usr/local/lib/python3.8/site-packages/nltk/tokenize/__init__.py", line 106, in sent_tokenize
    tokenizer = load("tokenizers/punkt/{0}.pickle".format(language))
  File "/usr/local/lib/python3.8/site-packages/nltk/data.py", line 752, in load
    opened_resource = _open(resource_url)
  File "/usr/local/lib/python3.8/site-packages/nltk/data.py", line 877, in _open
    return find(path_, path + [""]).open()
  File "/usr/local/lib/python3.8/site-packages/nltk/data.py", line 585, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/PY3/english.pickle

  Searched in:
    - '/Users/K-Lab/nltk_data'
    - '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/nltk_data'
    - '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/share/nltk_data'
    - '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************

🍵~$ 
```

**Comment by iwasakishuto** [comment]
> failed to build remote driver

Building a **Remote Driver** is succeed only in the [Docker environment](https://github.com/iwasakishuto/Translation-Gummy/tree/master/docker) (see [notebook](https://nbviewer.jupyter.org/github/iwasakishuto/Translation-Gummy/blob/master/examples/%5BDocker%5D%20Use.Translation-Gummy.via.Docker.ipynb)), so **you don't have to worry about it :)** Translation-Gummy will automatically choose local driver.

```python
[success] local driver can be built.
[failure] remote driver can't be built.
DRIVER_TYPE: local  <- Translation-Gummy chooses local driver.
```

**Comment by iwasakishuto** [comment]
> failed to use `nltk`

NLTK requires to download some resources to tokenize, so please follow the instructions and download additional data.

```python
import nltk
nltk.download('punkt')
```

I intended to do this (download some resources) automatically with the following script. But not works :( Thank you for letting me know it.

```python
# @gummy.utils.generic_utils.py
try:
    from nltk.tokenize import sent_tokenize, word_tokenize
    _ = sent_tokenize(text="gummy")
    _ = word_tokenize(text="gummy")
except LookupError:
    print("You have to download some resources for using NLTK.")
    import nltk
    nltk.download('punkt')
    from nltk.tokenize import sent_tokenize, word_tokenize
```

**Comment by harazono** [comment]
Thank you for your advice.
I downloaded punkt manually and it works.
